# Generated by Django 4.1.2 on 2022-11-30 01:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('foodID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sodium', models.DecimalField(decimal_places=2, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=5)),
                ('k', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calcium', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sugar', models.IntegerField(default=0)),
                ('cholesterol', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calories', models.IntegerField(default=0)),
                ('carbohydrates', models.IntegerField(default=0)),
                ('fiber', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('foodEntryID', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.today)),
                ('mealType', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Morbidity',
            fields=[
                ('morbidityID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('datediagnosed', models.DateTimeField(blank=True, default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Serving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kind', models.CharField(max_length=20)),
                ('foodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KidneyApp.food')),
                ('foodentryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KidneyApp.foodentry')),
            ],
            options={
                'unique_together': {('foodID', 'foodentryID')},
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personid', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('morbidities', models.ManyToManyField(to='KidneyApp.morbidity')),
            ],
        ),
        migrations.CreateModel(
            name='LabVitals',
            fields=[
                ('vitalid', models.BigAutoField(primary_key=True, serialize=False)),
                ('K', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Phos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Na', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Albumin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('BloodSugar', models.IntegerField(default=0)),
                ('BloodPressure', models.CharField(max_length=10)),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Date', models.DateTimeField(blank=True, default=datetime.datetime.today)),
                ('personID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='KidneyApp.person')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('entryID', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.today)),
                ('notes', models.CharField(max_length=3000)),
                ('status', models.CharField(max_length=25)),
                ('personID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='KidneyApp.person')),
            ],
        ),
        migrations.AddField(
            model_name='foodentry',
            name='foods',
            field=models.ManyToManyField(blank=True, through='KidneyApp.Serving', to='KidneyApp.food'),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='personID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='KidneyApp.person'),
        ),
        migrations.CreateModel(
            name='ExerciseEntry',
            fields=[
                ('exerciseID', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.today)),
                ('personID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='KidneyApp.person')),
            ],
        ),
    ]
