# Generated by Django 4.1.2 on 2022-11-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KidneyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labvitals',
            name='creatinine',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
