# Generated by Django 4.1.2 on 2022-11-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KidneyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
