# Generated by Django 4.1.2 on 2022-11-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KidneyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labvitals',
            name='Creatinine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='labvitals',
            name='Weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
