# Generated by Django 4.1.2 on 2022-11-30 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KidneyApp', '0002_labvitals_creatinine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labvitals',
            name='creatinine',
        ),
    ]
