# Generated by Django 4.1.2 on 2022-11-30 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KidneyApp', '0002_alter_patient_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='morbidities',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patientID',
        ),
        migrations.RemoveField(
            model_name='exerciseentry',
            name='patientID',
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='patientID',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='patientID',
        ),
        migrations.RemoveField(
            model_name='labvitals',
            name='patientID',
        ),
        migrations.RemoveField(
            model_name='labvitals',
            name='professionalID',
        ),
        migrations.AddField(
            model_name='exerciseentry',
            name='personID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='KidneyApp.person'),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='personID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='KidneyApp.person'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='personID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='KidneyApp.person'),
        ),
        migrations.AddField(
            model_name='labvitals',
            name='personID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='KidneyApp.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='main_photo',
            field=models.ImageField(default=None, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='person',
            name='morbidities',
            field=models.ManyToManyField(to='KidneyApp.morbidity'),
        ),
        migrations.AddField(
            model_name='person',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.DeleteModel(
            name='MedicalProfessional',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
