# Generated by Django 4.1.2 on 2022-11-30 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KidneyApp', '0003_remove_patient_morbidities_remove_patient_patientid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='main_photo',
        ),
    ]
