# Generated by Django 4.1.2 on 2022-11-30 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KidneyApp', '0003_remove_labvitals_creatinine'),
        ('KidneyApp', '0004_alter_labvitals_weight'),
    ]

    operations = [
    ]
